# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
logging:
  level:
    org.springframework: INFO
    com.ibatis: INFO

spring:
  application:
    name: soa-provider-service

server:
  tomcat:
    accesslog:
      directory: /logs
      suffix: .log
  context-path: /soaproviderservice
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.100.67.193:8761/eurekaservice/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5


